CREATE USER root WITH SUPERUSER PASSWORD 'root';

CREATE DATABASE appdb;
CREATE USER appuser WITH PASSWORD 'my-apps';
GRANT CONNECT ON DATABASE appdb TO appuser;
GRANT ALL PRIVILEGES ON DATABASE appdb TO appuser;
GRANT USAGE ON SCHEMA public TO appuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO appuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO appuser;

CREATE DATABASE conduktordb;
CREATE USER conduktor WITH PASSWORD 'my-conduktor-password';
GRANT CONNECT ON DATABASE conduktordb TO conduktor;
GRANT ALL PRIVILEGES ON DATABASE conduktordb TO conduktor;
GRANT USAGE ON SCHEMA public TO conduktor;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO conduktor;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO conduktor;
