global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 30s
  external_labels:
    monitor: "prom-stack"

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8999']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'docker-daemon'
    static_configs:
      - targets: ['172.17.0.1:9323']
  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:9273']
  - job_name: 's3prometheus'
    static_configs:
    - targets: ['s3prometheus:9655']
  - job_name: 'postgres'
    static_configs:
      - targets: ["postgres-exporter:9187"]

otlp:
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment.name

storage:
  tsdb:
    out_of_order_time_window: 30m