apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo-traces
    type: tempo
    url: http://tempo:3200
    editable: true
    isDefault: false

panels:
  - title: Recent Traces
    type: table
    datasource: tempo-traces
    queryType: search
    targets:
      - expr: ''

  - title: Explore Traces
    type: trace
    datasource: tempo-traces

  - title: Latency Histogram (ms, 5m)
    type: timeseries
    datasource: tempo-traces
    queryType: traceql
    targets:
      - expr: "topk(5, count_over_time({ resource.service.name=\"$service\" } | duration [5m]) by (trace.name))"