{
 "title": "Tempo Tracing Production Dashboard",
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(resource.service.name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Recent Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{ resource.service.name = \"$service\" }",
     "filters": [
      { "id": "0c2693a4", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Total Traces (5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({ resource.service.name=\"$service\" }[5m])",
     "filters": [
      {
       "id": "32fd0545",
       "operator": "=",
       "scope": "span",
       "value": []
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      }
     ],
     "limit": 40,
     "metricsQueryType": "range",
     "query": "{ } | count_over_time() by (resource.service.name)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Trace Errors (5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({ resource.service.name=\"$service\", status.code=\"ERROR\" }[5m])",
     "filters": [
      { "id": "295cc4b1", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "my-example-server-test" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Average Trace Latency (ms, 5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({ resource.service.name=\"$service\" } | duration [5m])"
    }
   ]
  },
  {
   "title": "P95 Trace Latency (ms, 5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, { resource.service.name=\"$service\" } | duration [5m])"
    }
   ]
  },
  {
   "title": "Latency Histogram (ms, 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "topk(5, count_over_time({ resource.service.name=\"$service\" } | duration [5m]) by (trace.name))"
    }
   ]
  },
  {
   "title": "Explore Traces",
   "type": "trace",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "{ resource.service.name=\"$service\" }"
    }
   ]
  },
  {
   "title": "Traces: GET /",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{ resource.service.name = \"$service\", name = \"GET /\" }",
     "filters": [
      { "id": "122668b7", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "my-example-server-test" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "GET /" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  }
 ]
}